In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6,7,8]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
l1=[1,2,3,4,5,6,7,8,3.44,"pran"]

In [5]:
a2=np.array(l1)

In [6]:
a1=np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
# dimension of array via ndim function
a1.ndim

2

In [8]:
a1.size

8

In [9]:
a1.shape

(2, 4)

In [10]:
np.random.randint(2,5600,[3,2,4])

array([[[1531, 2980, 3384, 1217],
        [1115, 5203,  331, 1455]],

       [[3350, 5575, 5554, 1593],
        [3488, 1841, 2973, 1756]],

       [[2759, 1359, 4556, 5460],
        [ 616, 2912, 1141, 3110]]])

In [11]:
np.random.rand(2,3)

array([[0.65784877, 0.40011105, 0.92188157],
       [0.48408995, 0.17201174, 0.06632923]])

In [12]:
a4=np.random.randn(4,4)

In [13]:
a4.reshape(2,-15)

array([[-1.13803066, -0.01931577, -0.44795759,  0.37010216,  1.05502599,
        -1.70861828,  1.27438081, -0.37963408],
       [-2.29466435,  0.14489812,  1.16246046,  1.16235494,  0.88323934,
         1.2030912 ,  0.50717166,  0.25425543]])

In [14]:
a4.reshape(2,8)

array([[-1.13803066, -0.01931577, -0.44795759,  0.37010216,  1.05502599,
        -1.70861828,  1.27438081, -0.37963408],
       [-2.29466435,  0.14489812,  1.16246046,  1.16235494,  0.88323934,
         1.2030912 ,  0.50717166,  0.25425543]])

In [15]:
a4.reshape(2,2,4)

array([[[-1.13803066, -0.01931577, -0.44795759,  0.37010216],
        [ 1.05502599, -1.70861828,  1.27438081, -0.37963408]],

       [[-2.29466435,  0.14489812,  1.16246046,  1.16235494],
        [ 0.88323934,  1.2030912 ,  0.50717166,  0.25425543]]])

In [16]:
a2

array(['1', '2', '3', '4', '5', '6', '7', '8', '3.44', 'pran'],
      dtype='<U32')

In [17]:
a2[0]

'1'

In [18]:
a2[1:4:2]

array(['2', '4'], dtype='<U32')

In [19]:
a2[::-1]

array(['pran', '3.44', '8', '7', '6', '5', '4', '3', '2', '1'],
      dtype='<U32')

In [20]:
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
a1[1]

array([5, 6, 7, 8])

In [22]:
a1[:,2:5]

array([[3, 4],
       [7, 8]])

In [23]:
a5=np.random.randint(2,90,(6,5))

In [24]:
a5

array([[24, 21, 81, 41, 30],
       [40, 83, 43, 33, 44],
       [10, 81, 85,  5, 55],
       [ 3, 36, 44, 29, 38],
       [64, 55, 20, 53,  3],
       [87, 10, 64, 26,  7]])

In [25]:
a5[a5>40]

array([81, 41, 83, 43, 44, 81, 85, 55, 44, 64, 55, 53, 87, 64])

In [30]:
a5[0][3]=-1

In [31]:
a5

array([[24, 21, 81, -1, 30],
       [40, 83, 43, 33, 44],
       [10, 81, 85,  5, 55],
       [ 3, 36, 44, 29, 38],
       [64, 55, 20, 53,  3],
       [87, 10, 64, 26,  7]])

In [34]:
a6=np.random.randint(2,3,(4,4))

In [35]:
a6

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [39]:
#Method for element multiplication
a4*a6

array([[-2.27606132, -0.03863153, -0.89591517,  0.74020431],
       [ 2.11005197, -3.41723656,  2.54876161, -0.75926816],
       [-4.5893287 ,  0.28979625,  2.32492092,  2.32470989],
       [ 1.76647868,  2.40618239,  1.01434333,  0.50851086]])

In [40]:
#Method for matrix multiplication
a4@a6

array([[-2.47040371, -2.47040371, -2.47040371, -2.47040371],
       [ 0.48230886,  0.48230886,  0.48230886,  0.48230886],
       [ 0.35009837,  0.35009837,  0.35009837,  0.35009837],
       [ 5.69551526,  5.69551526,  5.69551526,  5.69551526]])

In [42]:
a6+100

array([[102, 102, 102, 102],
       [102, 102, 102, 102],
       [102, 102, 102, 102],
       [102, 102, 102, 102]])

In [43]:
a6*2

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [44]:
a7=np.zeros((4,4))

In [45]:
a7

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
a8=np.ones((4,5))

In [47]:
a8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
a9=a8+np.array([1,2,3,4,5])

In [49]:
a9

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [60]:
a10=np.array([[1,2,3,4]]).T

In [61]:
a10

array([[1],
       [2],
       [3],
       [4]])

In [62]:
a8+a10

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [64]:
np.sqrt(a9)

array([[1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974],
       [1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974],
       [1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974],
       [1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974]])

In [72]:
np.log10(a9)

array([[0.30103   , 0.47712125, 0.60205999, 0.69897   , 0.77815125],
       [0.30103   , 0.47712125, 0.60205999, 0.69897   , 0.77815125],
       [0.30103   , 0.47712125, 0.60205999, 0.69897   , 0.77815125],
       [0.30103   , 0.47712125, 0.60205999, 0.69897   , 0.77815125]])

In [73]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [75]:
np.arange(1,10,2.3)

array([1. , 3.3, 5.6, 7.9])

In [78]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [79]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [80]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])